#! /bin/zsh

if [[ ${PWD##*/} != "api" ]]; then
    echo "Failed: please run this script from DeepKS/api"
else
    export UN="dockeruser"
    cd ../../
    python3 -m DeepKS.api.main \
        -s DTDMKRLSMEIEKEK \
        -k MSDVAIVKEGWLHKRGEYIKTWRPRYFLLKNDGTFIGYKERPQDVDQREAPLNNFSVAQCQLMKTERPRPNTFIIRCLQWTTVIERTFHVETPEEREEWTTAIQTVADGLKKQEEEEMDFRSGSPSDNSGAEEMEVSLAKPKHRVTMNEFEYLKLLGKGTFGKVILVKEKATGRYYAMKILKKEVIVAKDEVAHTLTENRVLQNSRHPFLTALKYSFQTHDRLCFVMEYANGGELFFHLSRERVFSEDRARFYGAEIVSALDYLHSEKNVVYRDLKLENLMLDKDGHIKITDFGLCKEGIKDGATMKTFCGTPEYLAPEVLEDNDYGRAVDWWGLGVVMYEMMCGRLPFYNQDHEKLFELILMEEIRFPRTLGPEAKSLLSGLLKKDPKQRLGGGSEDAKEIMQHRFFAGIVWQHVYEKKLSPPFKPQVTSETDTRYFDEEFTAQMITITPPDQDDSMECVDSERRPHFPQFSYSASGTA \
        -p inorder \
        --scores \
        --groups \
        --device cuda:4 \
        --pre-trained-nn bin/deepks_nn_weights.15.cornichon \
        --pre-trained-gc bin/pseudo_gc.cornichon \
        --verbose
fi
